<a href="https://colab.research.google.com/github/vernikagupta/Deep_Learning_with_Maths/blob/master/NeuralNetwork_from_Scratch_ipynb_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**The Network architecture is**

##### 3 neurons in input layer plus one bias
##### 4 neurons in hidden layer plus one bias
##### 1 neuron in output layer
##### cost function is (target - output)<sup>2</sup>
##### activation function Sigmoid

In [ ]:
import numpy as np

In [ ]:
def Sigmoid(x):
  out = 1.0/(1+np.exp(-x))
  return out

In [ ]:
def Sigmoid_derivative(x):
  return x * (1.0-x)

In [ ]:
class NN():
  def __init__(self, input, target ):
    self.input = input   # input data
    self.target = target   # labels initialization
    self.bias1 = np.random.rand(1)
    self.bias2 = np.random.rand(1)
    self.weights1 = np.random.rand(self.input.shape[1],4) # initialize weights for hidden layers
    #self.weights1 = np.zeros((self.input.shape[1],4))  # use this if wants to check effect of zero initialization
    self.weights2 = np.random.rand(4,1)  # initialize weights for output layer
    #self.weights2 = np.zeros((4,1))  
    self.output = np.zeros(self.target.shape)    # initialize output with zeros

  def feedForward(self):
    self.layer1 = Sigmoid(np.dot(self.input, self.weights1) + self.bias1)
    self.output = Sigmoid(np.dot(self.layer1, self.weights2) + self.bias2)
    cost = 2*np.sum((self.target - self.output))
    return (self.output, cost)

  def backpropagation(self):
    # chain rule to calculate derivative of cost function with weights
    cost_act_mul = (2*(self.target-self.output)) * Sigmoid_derivative(self.output)
    d_weights2 = np.dot(self.layer1.T, cost_act_mul)
    #print(d_weights2.shape)
    d_weights1 = np.dot(self.input.T,  
                        (np.dot(2*(self.target - self.output) * Sigmoid_derivative(self.output), self.weights2.T)
                         * Sigmoid_derivative(self.layer1)))

    # update the weights with the derivative (slope) of the loss function
    print("weight1 before iteration:\n",self.weights1)
   
    self.weights1 += d_weights1
    print("\nweight1 after iteration:\n",self.weights1)
    #print(d_weights2.shape)
    print("\nweight2 before iteration:\n",self.weights2)
    self.weights2 += d_weights2
    
    
    print("\nweight2 after iteration:\n",self.weights2)
    



In [ ]:
 x = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
 y = np.array([[0],[1],[1],[0]]) 

In [ ]:
nn = NN(x,y)
for i in range(1500):
  print("i",i)
  output, cost = nn.feedForward()
  nn.backpropagation()

print("\noutput",output)
print("\n cost: ", cost)

Streaming output truncated to the last 5000 lines.
 [[ 5.9018265   2.25459418  5.88579309 -3.29015555]
 [ 5.96569015  1.61833898 -2.1304435   6.22709995]
 [-1.61226884 -3.08633902 -0.58498401  0.50336609]]

weight1 after iteration:
 [[ 5.90203454  2.2549175   5.88622172 -3.29045762]
 [ 5.96590839  1.6188718  -2.13073843  6.22748231]
 [-1.61233077 -3.08704868 -0.58490336  0.5034734 ]]

weight2 before iteration:
 [[10.77751419]
 [-3.35795819]
 [-5.94693776]
 [-6.42060214]]

weight2 after iteration:
 [[10.77864623]
 [-3.35871139]
 [-5.9475241 ]
 [-6.42110289]]
i 1274
weight1 before iteration:
 [[ 5.90203454  2.2549175   5.88622172 -3.29045762]
 [ 5.96590839  1.6188718  -2.13073843  6.22748231]
 [-1.61233077 -3.08704868 -0.58490336  0.5034734 ]]

weight1 after iteration:
 [[ 5.90224232  2.25524053  5.8866498  -3.29075931]
 [ 5.96612636  1.61940406 -2.13103301  6.22786418]
 [-1.61239264 -3.08775758 -0.58482278  0.50358058]]

weight2 before iteration:
 [[10.77864623]
 [-3.35871139]
 [-5.9475

**Running code with zero weight initializations:**
##### Added bias in both layers
##### weight change will be small and weight will become nagative
##### output is [0.5, 0.5, 0.5, 0.5] even after 70000 epochs

**Running code with Random Weights**
##### with random weights and same bias
##### output in 1000 epoch is [0,0.9,0.9,0]